name: restcountries
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: gufy <email@example.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  dio: 2.1.3

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
  mockito: 4.1.0
